/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIndexRouteImport } from './routes/listing/index'
import { Route as ListingProductIdRouteImport } from './routes/listing/$productId'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIndexRoute = ListingIndexRouteImport.update({
  id: '/listing/',
  path: '/listing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingProductIdRoute = ListingProductIdRouteImport.update({
  id: '/listing/$productId',
  path: '/listing/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/registration': typeof RegistrationRoute
  '/listing/$productId': typeof ListingProductIdRoute
  '/listing': typeof ListingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/registration': typeof RegistrationRoute
  '/listing/$productId': typeof ListingProductIdRoute
  '/listing': typeof ListingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/registration': typeof RegistrationRoute
  '/listing/$productId': typeof ListingProductIdRoute
  '/listing/': typeof ListingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/order'
    | '/registration'
    | '/listing/$productId'
    | '/listing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/order'
    | '/registration'
    | '/listing/$productId'
    | '/listing'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/order'
    | '/registration'
    | '/listing/$productId'
    | '/listing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  RegistrationRoute: typeof RegistrationRoute
  ListingProductIdRoute: typeof ListingProductIdRoute
  ListingIndexRoute: typeof ListingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/': {
      id: '/listing/'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof ListingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$productId': {
      id: '/listing/$productId'
      path: '/listing/$productId'
      fullPath: '/listing/$productId'
      preLoaderRoute: typeof ListingProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  RegistrationRoute: RegistrationRoute,
  ListingProductIdRoute: ListingProductIdRoute,
  ListingIndexRoute: ListingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
